name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        platform:
        - ubuntu-latest
        - macos-latest
        include:
          - platform: windows-latest
            node-version: 20.x
          - platform: windows-latest
            node-version: 21.x

      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests Unix (complete coverage)
        if: matrix.platform != 'windows-latest'
        run: npm test -- -c -t0

      - name: Run Tests Windows (incomplete coverage)
        if: matrix.platform == 'windows-latest'
        run: npm test -- -c -t0 --allow-incomplete-coverage
